const fs = require('fs');
const P = 'E:/1/mud/2/JianLai mud/index.html';
let h = fs.readFileSync(P, 'utf8');

const scenes = [
"  // —— 文圣：读书人的道理 ——",
"  '文圣':{",
"    'dadao':{ entry:true, title:'老秀才的一问',",
"      cond:function(){ return true; },",
"      lines:[",
"        '（穗山脚下，老秀才拍拍身边的石头示意你坐，慢悠悠掏出一个酒葫芦）',",
"        '（他仰头灌了一口，忽然问）娃儿，你说这世上的道理，是书里的多，还是路走出来的多？'",
"      ],",
"      options:[",
"        { text:'书里的道理是灯，路走出来的才是腿——缺一不可。', effect:function(){",
"            gainAff('文圣',15); player.exp+=50; gainFame(4);",
"            log('（老秀才眯眼笑了）好娃儿。灯照路，腿走路——读书读到这份上，才算开窍。','npc','文圣');",
"            logSuccess('好感 +15，经验 +50，侠名 +4。');",
"        } },",
"        { text:'纸上得来终觉浅——我信脚下多些。', effect:function(){",
"            gainAff('文圣',10); player.exp+=60;",
"            log('（他也不恼，反倒点头）不读死书，好。可你别忘了，脚下走的路，也是前人书里写下的。','npc','文圣');",
"            logSuccess('好感 +10，经验 +60。');",
"        } },",
"        { text:'道理都是强者说了算——拳头大的有理。', effect:function(){",
"            gainAff('文圣',-5); player.exp+=15;",
"            log('（老秀才摇头，语气竟有几分悲悯）娃儿，道理要是只归强者，这天下早就没有读书人了。','npc','文圣');",
"            logSuccess('好感 -5，经验 +15。');",
"        } }",
"      ] }",
"  },",
"  // —— 曹慈：断头路上的拳 ——",
"  '曹慈':{",
"    'duantou':{ entry:true, title:'断头路',",
"      cond:function(){ return (player.aff['曹慈']||0)>=20 || player.level>=10; },",
"      lines:[",
"        '（剑气长城城头，曹慈收了架势，额角见汗——你竟是头一个见他用力的外人）',",
"        '（他看着云海，忽然开口）武夫这条路，走到头是断头路。我偏要走。你说，明知是断头路还要走的人，是蠢，还是别的什么？'",
"      ],",
"      options:[",
"        { text:'不是蠢——是要给后来的人，把路续上。', effect:function(){",
"            gainAff('曹慈',16); player.exp+=60; gainFame(5);",
"            log('（他静静看了你很久，忽然一拳轻轻捶在你胸口，力道却透着郑重）这话，我记下了。','npc','曹慈');",
"            logSuccess('好感 +16，经验 +60，侠名 +5。');",
"        } },",
"        { text:'是孤独。走到最前头的人，注定孤独。', effect:function(){",
"            gainAff('曹慈',10); player.exp+=45;",
"            log('（他望向远山，半晌，轻轻嗯了一声）孤独……倒也没觉得。拳在，就不孤单。','npc','曹慈');",
"            logSuccess('好感 +10，经验 +45。');",
"        } },",
"        { text:'是蠢。练气士飞天遁地，何必跟自己较劲。', effect:function(){",
"            gainAff('曹慈',-4); player.exp+=15;",
"            log('（他收回目光，语气平平）各走各的路。你的天上有仙，我的脚下有山。','npc','曹慈');",
"            logSuccess('好感 -4，经验 +15。');",
"        } }",
"      ] }",
"  },",
"  // —— 陆沉：红线一问 ——",
"  '陆沉':{",
"    'hongxian':{ entry:true, title:'月老的红线',",
"      cond:function(){ return (player.aff['陆沉']||0)>=15 || player.level>=8; },",
"      lines:[",
"        '（龙虎山松下，陆沉指间缠着一根几乎看不见的红线，冲你眨眨眼）',",
"        '（他笑吟吟地问）我这根红线，牵过天上的仙、山上的妖、市井的人——你说，姻缘这东西，是天定的，还是人求的？'",
"      ],",
"      options:[",
"        { text:'天定的缘，人求的分——缘是天给的起点，分是自己走的路。', effect:function(){",
"            gainAff('陆沉',15); player.exp+=45; gainFame(3);",
"            log('（他抚掌大笑）妙！妙！就冲这句话，下回你若有心上人，我给你牵根最结实的！','npc','陆沉');",
"            logSuccess('好感 +15，经验 +45，侠名 +3。');",
"        } },",
"        { text:'我的姻缘，不劳仙长费心——我自己牵。', effect:function(){",
"            gainAff('陆沉',8); player.exp+=35;",
"            log('（他挑眉，笑意更浓）好志气！那我把线收好——等你哪天求到我头上，可要加倍谢媒钱。','npc','陆沉');",
"            logSuccess('好感 +8，经验 +35。');",
"        } },",
"        { text:'儿女情长，英雄气短——少来这套。', effect:function(){",
"            gainAff('陆沉',-3); player.exp+=15;",
"            log('（他嘿嘿一笑，也不恼）气短不短，牵过线的都知道——这滋味，你迟早要尝。','npc','陆沉');",
"            logSuccess('好感 -3，经验 +15。');",
"        } }",
"      ] }",
"  },",
"  // —— 裴杯：拳与天下 ——",
"  '裴杯':{",
"    'quantianxia':{ entry:true, title:'拳头的分量',",
"      cond:function(){ return (player.aff['裴杯']||0)>=15 || player.level>=12; },",
"      lines:[",
"        '（文庙御街的演武场边，裴杯收势而立，一圈人屏息退开。她瞥见你，招了招手）',",
"        '（她缓缓吐出一口白气）我这双拳头，打过山巅境的老宗师，也打过后生晚辈。你说，拳头练到最硬，是为了打谁？'",
"      ],",
"      options:[",
"        { text:'为了不用打——拳越硬，天下越太平。', effect:function(){",
"            gainAff('裴杯',16); player.exp+=55; gainFame(6);",
"            log('（她眼中罕见地浮起一丝笑意）好答案。拳头是让人讲道理的——不是让人不讲道理的。','npc','裴杯');",
"            logSuccess('好感 +16，经验 +55，侠名 +6。');",
"        } },",
"        { text:'为了打该打之人——妖族犯境，拳头就是国门。', effect:function(){",
"            gainAff('裴杯',12); player.exp+=50;",
"            log('（她点头）不错。有这份心，你这双拳头，就不会练歪。','npc','裴杯');",
"            logSuccess('好感 +12，经验 +50。');",
"        } },",
"        { text:'为了打服所有人——弱者哪有资格讲道理。', effect:function(){",
"            gainAff('裴杯',-5); player.exp+=15;",
"            log('（她神色一冷）拳头打服的，只是暂时的沉默。等你哪天老了、伤了，你再想想今日这句话。','npc','裴杯');",
"            logSuccess('好感 -5，经验 +15。');",
"        } }",
"      ] }",
"  },",
"  // —— 姜尚真：舍得生意 ——",
"  '姜尚真':{",
"    'shengyi':{ entry:true, title:'赔本的买卖',",
"      cond:function(){ return (player.aff['姜尚真']||0)>=15 || player.gold>=200; },",
"      lines:[",
"        '（落魄山客卿居，姜尚真对着一本账册长吁短叹，见你进来，眼睛一亮）',",
"        '（他把账册一合）说个正经的——我这辈子做过最赔本的买卖，就是把一身修为跌境，换这把飞剑只剩一片柳叶。你说，我是赚了还是赔了？'",
"      ],",
"      options:[",
"        { text:'赚了。一片飞升境的柳叶，胜过满筐凡铁。', effect:function(){",
"            gainAff('姜尚真',14); player.exp+=45; player.gold+=30;",
"            log('（他大喜，一拍桌子）知音啊！这就叫把家底换成利刃——来，这三十两算分红！','npc','姜尚真');",
"            logSuccess('好感 +14，经验 +45，银两 +30。');",
"        } },",
"        { text:'赔了。境界是根本，飞剑是枝叶——本末倒置。', effect:function(){",
"            gainAff('姜尚真',6); player.exp+=40;",
"            log('（他歪头想想，忽然乐了）也有理。所以我赔了境界，却赚了个\"敢\"字——这买卖，怎么算都不亏。','npc','姜尚真');",
"            logSuccess('好感 +6，经验 +40。');",
"        } },",
"        { text:'商人逐利而已，哪来赚赔的道理。', effect:function(){",
"            gainAff('姜尚真',-4); player.exp+=12;",
"            log('（他做出一副伤心状）哎哟，扎心了。账房先生都不如你狠——亏得我还想带你入伙。','npc','姜尚真');",
"            logSuccess('好感 -4，经验 +12。');",
"        } }",
"      ] }",
"  }"
].join('\r\n');

if (h.indexOf('文圣：读书人的道理') > -1) { console.log('FATAL: already present'); process.exit(1); }
const d = h.indexOf('const DRAMA={');
const c = h.indexOf('\r\n];', d);
if (c < 0) { console.log('FATAL: drama close not found'); process.exit(1); }
let prefix = h.slice(0, c).replace(/\s+$/, '');
if (!/  }}$/.test(prefix)) { console.log('FATAL: prefix tail: ' + JSON.stringify(prefix.slice(-40))); process.exit(1); }
h = prefix + ',\r\n' + scenes + '\r\n];' + h.slice(c + 4);
fs.writeFileSync(P, h, 'utf8');

// 校验
const dI = h.indexOf('const DRAMA={');
const etI = h.indexOf('const EVENT_TEMPLATES');
const wI = h.indexOf("'文圣':{", dI);
const cnt = (h.match(/文圣：读书人的道理/g) || []).length;
console.log('inside DRAMA:', wI > dI && wI < etI, '| count:', cnt);
