const fs = require('fs');
const s = fs.readFileSync('index.html', 'utf8');
const out = [];
out.push('--- startNewGame ---');
const i = s.indexOf('function startNewGame');
out.push(s.slice(i, i + 620));
out.push('--- PATHS 剑修 ---');
const j = s.indexOf("'剑修':{tag");
out.push(j > -1 ? s.slice(j, j + 300) : '(not found)');
out.push('--- applyStartup 章节静默同步? ---');
const k = s.indexOf('game.chapter=Math.max(game.chapter');
out.push(k > -1 ? s.slice(k - 120, k + 160) : '(未找到)');
out.push('--- discoverQuests 批量日志? ---');
const m = s.indexOf('新的线索 ×');
out.push(m > -1 ? '(已批量)' : '(未批量)');
out.push('--- 标题屏槽位选择器? ---');
const p = s.indexOf('存档栏槽位');
out.push(p > -1 ? '(有槽位选择器)' : '(无)');
fs.writeFileSync('_tutorials/_chk3.txt', out.join('\n\n'));
console.log('done');
